/**
 * Created by admin on 2017/8/22.
 */

var vm = new Vue({
	el:'#app',
	data:{
		title:'this is title',
		content:[{
			name:'demo1'
		},{
			name:'demo2'
		}]
	},
	beforeCreate:function(){
		console.log('beforeCreate-----------------');
		console.log('this',this);
		console.log('data',this.$data);
		console.log('el',this.$el);
	},
	created:function(){
		console.log('created-----------------------');
		console.log('this',this);
		console.log('data',this.$data);
		console.log('el',this.$el);
	},
	beforeMount:function(){
		console.log('beforeMount--------------------');
		console.log('this',this);
		console.log('data',this.$data);
		console.log('el',this.$el);
	},
	mounted:function(){
		console.log('mounted-------------------------');
		console.log('this',this);
		console.log('data',this.$data);
		console.log('el',this.$el);
	},
	beforeUpdate:function(){
		console.log('beforeUpdate----------------------');
		console.log('this',this);
		console.log('data',this.$data);
		console.log('el',this.$el);
	},
	updated:function(){
		console.log('updated---------------------------');
		console.log('this',this);
		console.log('data',this.$data);
		console.log('el',this.$el);
	}
});